spring:
  datasource:
    password: tkdgus112
    url: jdbc:mysql://localhost:3306/codejavadb
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 369707062662-tkvc356t9cie2ffnd1pj6suhk8nbl5b0.apps.googleusercontent.com
            clientSecret: huFyGKt6HVGFAF63m_1vszr9
            scope:
              - email
              - profile

